# Generated by Django 6.0 on 2025-12-26 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_ml_commission_and_movement_metrics'),
        ('inventory', '0012_purchase_stockmovement_purchase_purchaseitem'),
    ]

    operations = [
    ]
