# Generated by Codex on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_product_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
