# Generated by Codex on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0028_customer_phone_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="cost_unit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
