# Generated by Django 4.2.30 on 2026-09-07, trimmed to the multi-company change only.
# (makemigrations also picked up unrelated pre-existing model drift — afipinvoice
# constraints, id field types on payments, etc. — that isn't part of this work.)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_stylmoda(apps, schema_editor):
    """La única cuenta que existía hasta ahora era Stylmoda: todo lo que ya
    está en la base se etiqueta con ella para no perder continuidad histórica.
    El depósito COMUN queda sin company: es el pool compartido.
    """
    Company = apps.get_model("inventory", "Company")
    Warehouse = apps.get_model("inventory", "Warehouse")
    MercadoLibreConnection = apps.get_model("inventory", "MercadoLibreConnection")
    MercadoLibreItem = apps.get_model("inventory", "MercadoLibreItem")
    Sale = apps.get_model("inventory", "Sale")
    Purchase = apps.get_model("inventory", "Purchase")

    stylmoda, _ = Company.objects.get_or_create(name="Stylmoda")

    Warehouse.objects.filter(type="MERCADOLIBRE").update(company=stylmoda)
    MercadoLibreConnection.objects.all().update(company=stylmoda)
    MercadoLibreItem.objects.all().update(company=stylmoda)
    Sale.objects.all().update(company=stylmoda)
    Purchase.objects.all().update(company=stylmoda)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0065_supplierproduct_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cuit', models.CharField(blank=True, default='', max_length=20)),
                ('fiscal_condition', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='mercadolibreconnection',
            name='user',
            field=models.ForeignKey(help_text='Usuario que conectó la cuenta. Ya no identifica la cuenta: eso lo hace company.', on_delete=django.db.models.deletion.CASCADE, related_name='ml_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('MERCADOLIBRE', 'MercadoLibre'), ('COMUN', 'Comun')], max_length=20),
        ),
        migrations.AddField(
            model_name='mercadolibreconnection',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ml_connection', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='mercadolibreitem',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Cuenta de MercadoLibre dueña de esta publicación.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ml_items', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Razón social a la que se imputa esta compra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Razón social bajo la que se factura esta venta. Se completa sola en ventas ML; en ventas propias se elige a mano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Dueña del depósito Full de esta cuenta. En blanco para el depósito COMUN, que es compartido.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='inventory.company'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('type', 'company'), name='warehouse_type_company_unique'),
        ),
        migrations.RunPython(backfill_stylmoda, noop_reverse),
    ]
