# Generated by Django 4.2.30 on 2026-09-09, trimmed to the fiscal multi-company
# change only. (makemigrations also picked up the same unrelated pre-existing
# model drift as 0066 — afipinvoice constraints, id field types on payments —
# that isn't part of this work.)

from django.db import migrations, models
import django.db.models.deletion


def backfill_stylmoda(apps, schema_editor):
    """Todo lo fiscal que ya está cargado es de Stylmoda, la única cuenta que
    existía hasta ahora."""
    Company = apps.get_model("inventory", "Company")
    AFIPInvoice = apps.get_model("inventory", "AFIPInvoice")
    TaxExpense = apps.get_model("inventory", "TaxExpense")
    IVAPayment = apps.get_model("inventory", "IVAPayment")

    stylmoda = Company.objects.filter(name="Stylmoda").first()
    if not stylmoda:
        return
    AFIPInvoice.objects.all().update(company=stylmoda)
    TaxExpense.objects.all().update(company=stylmoda)
    IVAPayment.objects.all().update(company=stylmoda)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_multi_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='afipinvoice',
            name='company',
            field=models.ForeignKey(blank=True, help_text="Empresa (CUIT propio) que recibió este comprobante — 'Mis Comprobantes' se descarga una vez por CUIT.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afip_invoices', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='ivapayment',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Cada empresa declara y paga su propio IVA por separado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iva_payments', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='taxexpense',
            name='company',
            field=models.ForeignKey(blank=True, help_text='En blanco si es un gasto general del negocio, no de una empresa puntual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_expenses', to='inventory.company'),
        ),
        migrations.RunPython(backfill_stylmoda, noop_reverse),
    ]
